services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_LISTEN_PORT=${PORT}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PORT}:${PORT}"
    networks:
      - pgadmin

networks:
  pgadmin:
    driver: bridge

volumes:
  pgadmin:
